name: controlsFile

on:
  push:
    paths: 
      - 'FHEM/**'
      - '.github/workflows/update.yml'

jobs:
  update:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Repostory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: update controls files
      uses: fhem/fhem-controls-actions@V2.2.1
      with:
        filename: controls_APSystemsFHEM.txt 
    - name: update CHANGED
      if: steps.extract_branch.outputs.branch == 'master'
      run: |
        LOG=$(date +"%Y-%m-%d") 
        LOG+=" - $(git log -1 --pretty=%B)"
        echo "$LOG" | cat - CHANGED > temp && mv temp CHANGED
    - name: git commit back
      run: |
        git config --global user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git ls-files --error-unmatch controls_APSystemsFHEM.txt || git add controls_APSystemFHEM.txt 
        git ls-files --error-unmatch CHANGED || git add CHANGED
        git diff --name-only --exit-code controls_APSystemFHEM.txt || git commit CHANGED controls_APSystemsFHEM.txt -m "Automatic updated controls and CHANGED" || true
    - name: Push  to branch 
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
